from __future__ import annotations

import io
from datetime import datetime, timezone
from typing import Any

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from docx.shared import Inches, Pt, RGBColor

from services.document_it.schemas import DocumentSection, GeneratedDocumentContent


def _set_cell_shading(cell, hex_color: str) -> None:
    shading = OxmlElement("w:shd")
    shading.set(qn("w:fill"), hex_color)
    shading.set(qn("w:val"), "clear")
    cell._tc.get_or_add_tcPr().append(shading)


def _add_horizontal_line(paragraph) -> None:
    p = paragraph._p
    p_pr = p.get_or_add_pPr()
    p_bdr = OxmlElement("w:pBdr")
    bottom = OxmlElement("w:bottom")
    bottom.set(qn("w:val"), "single")
    bottom.set(qn("w:sz"), "12")
    bottom.set(qn("w:space"), "1")
    bottom.set(qn("w:color"), "D0D5DD")
    p_bdr.append(bottom)
    p_pr.append(p_bdr)


def _write_section(document: Document, section: DocumentSection) -> None:
    heading = document.add_heading(section.heading, level=1)
    for run in heading.runs:
        run.font.color.rgb = RGBColor(0x10, 0x24, 0x40)

    if section.body:
        paragraph = document.add_paragraph(section.body)
        paragraph.paragraph_format.space_after = Pt(8)

    for bullet in section.bullets or []:
        text = str(bullet or "").strip()
        if text:
            document.add_paragraph(text, style="List Bullet")

    table = section.table
    if table and table.headers:
        rows = table.rows or []
        doc_table = document.add_table(rows=1 + len(rows), cols=len(table.headers))
        doc_table.style = "Table Grid"
        header_cells = doc_table.rows[0].cells
        for index, header in enumerate(table.headers):
            header_cells[index].text = str(header)
            for paragraph in header_cells[index].paragraphs:
                for run in paragraph.runs:
                    run.bold = True
                    run.font.size = Pt(10)
            _set_cell_shading(header_cells[index], "F2F4F7")

        for row_index, row in enumerate(rows):
            cells = doc_table.rows[row_index + 1].cells
            for col_index in range(len(table.headers)):
                value = row[col_index] if col_index < len(row) else ""
                cells[col_index].text = str(value or "")
                for paragraph in cells[col_index].paragraphs:
                    for run in paragraph.runs:
                        run.font.size = Pt(10)

        document.add_paragraph("")


def build_docx_bytes(
    content: GeneratedDocumentContent | dict[str, Any],
    *,
    template_title: str,
    space_name: str,
) -> bytes:
    payload = (
        content
        if isinstance(content, GeneratedDocumentContent)
        else GeneratedDocumentContent.model_validate(content)
    )

    document = Document()
    section = document.sections[0]
    section.top_margin = Inches(0.85)
    section.bottom_margin = Inches(0.85)
    section.left_margin = Inches(0.9)
    section.right_margin = Inches(0.9)

    style = document.styles["Normal"]
    style.font.name = "Calibri"
    style.font.size = Pt(11)

    title = document.add_heading(payload.title or template_title, level=0)
    title.alignment = WD_ALIGN_PARAGRAPH.LEFT
    for run in title.runs:
        run.font.color.rgb = RGBColor(0x10, 0x24, 0x40)

    if payload.subtitle:
        subtitle = document.add_paragraph(payload.subtitle)
        for run in subtitle.runs:
            run.italic = True
            run.font.color.rgb = RGBColor(0x66, 0x70, 0x85)

    meta_bits = [
        f"Template: {template_title}",
        f"Space: {space_name or payload.meta.get('space') or 'Workspace'}",
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
    ]
    for key, value in (payload.meta or {}).items():
        if key.lower() in {"space", "template"}:
            continue
        if value:
            meta_bits.append(f"{key}: {value}")

    meta_paragraph = document.add_paragraph(" · ".join(meta_bits))
    for run in meta_paragraph.runs:
        run.font.size = Pt(9)
        run.font.color.rgb = RGBColor(0x98, 0xA2, 0xB3)
    _add_horizontal_line(meta_paragraph)

    if not payload.sections:
        document.add_paragraph("No sections were generated for this document.")
    else:
        for section_payload in payload.sections:
            _write_section(document, section_payload)

    footer = document.add_paragraph("")
    _add_horizontal_line(footer)
    note = document.add_paragraph("Generated by KukuNotes Document-it from workspace notes, tasks, and transcripts.")
    for run in note.runs:
        run.font.size = Pt(8)
        run.font.color.rgb = RGBColor(0x98, 0xA2, 0xB3)

    buffer = io.BytesIO()
    document.save(buffer)
    return buffer.getvalue()
