"""Structured-output capability helpers. Canonical implementation lives in schema_adapter."""

from services.llm.schema_adapter import (
    HTTP_ERROR,
    INCOMPLETE_STRUCTURED_OUTPUT,
    MALFORMED_JSON,
    MALFORMED_STRUCTURED_OUTPUT,
    PARSED_INSTANCE,
    PROVIDER_TIMEOUT,
    QUOTA_UNAVAILABLE,
    RATE_LIMITED,
    SCHEMA_ECHO,
    SCHEMA_VALIDATION_FAILED,
    STRING_LIST_FIELDS,
    STRUCTURED_SCHEMA_ECHO,
    STRUCTURED_SCHEMA_UNSUPPORTED,
    StructuredOutputCapability,
    WIRE_REQUIRED_COLLECTIONS,
    build_structured_plan,
    classify_llm_failure,
    classify_validation_error,
    drop_stage_for_structured_outcome,
    is_schema_echo,
    normalize_failure_reason,
    provider_local_recovery_eligible,
    structured_capabilities,
    structured_modes_for,
    structured_outcome_from_error,
)

__all__ = [
    "HTTP_ERROR",
    "INCOMPLETE_STRUCTURED_OUTPUT",
    "MALFORMED_JSON",
    "MALFORMED_STRUCTURED_OUTPUT",
    "PARSED_INSTANCE",
    "PROVIDER_TIMEOUT",
    "QUOTA_UNAVAILABLE",
    "RATE_LIMITED",
    "SCHEMA_ECHO",
    "SCHEMA_VALIDATION_FAILED",
    "STRING_LIST_FIELDS",
    "STRUCTURED_SCHEMA_ECHO",
    "STRUCTURED_SCHEMA_UNSUPPORTED",
    "StructuredOutputCapability",
    "WIRE_REQUIRED_COLLECTIONS",
    "build_structured_plan",
    "classify_llm_failure",
    "classify_validation_error",
    "drop_stage_for_structured_outcome",
    "is_schema_echo",
    "normalize_failure_reason",
    "provider_local_recovery_eligible",
    "structured_capabilities",
    "structured_modes_for",
    "structured_outcome_from_error",
]
